### ISSUE TITLE
Add room image

### ISSUE THREAD

**Issue by andtos90** [virtualdojo/virtualdojo-rooms#26]
Add a room image field and show it in the UI

**Comment by peterampazzo** [comment]
To go into details, this requires:
- [ ] Add new field in the addRoom form
- [ ] The handler function should upload the image into Firebase hosting and also associate it to the room (in the database)
- [ ] Display the image (?)

We should discuss how the image should be shown (as background? or as an icon?) 😄

**Comment by andtos90** [comment]
Will take a look at image upload later on
