### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by gbonanome** [virtualdojo/virtualdojo-rooms#33]
This repo miss a License 😱
@peterampazzo it's easy to do via the setup area of the project, it would let you choose and add automatically. My suggestion is to use either GNU GPLv3 or Apache 2.0.

**Comment by peterampazzo** [comment]
Thanks! As agreed on discord the license applied to the source code is GNU GPLv3. 
This issue has been solved with #34 PR 😉
